- name: create ec2 instance and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-09f061b0970f79d18
    sg_id: "sg-0bcb92b7b99177928"
    ami_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - frontend
  tasks:
   - name: create ec2 instance
     amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances
    