- name: variables to print
  hosts: web
  vars:
    COURSE: "Devops with Azure"
    DURATION: "140HRS"
    TRAINER: "Gopal"
  tasks:
  - name: print the information
    ansible.builtin.debug:
     msg: "Hi, i am learning {{COURSE}},Duration is: {{DURATION}},Trainer: {{TRAINER}} "