- name: variables to print
  hosts: web
  vars: #play level variables
    COURSE: "Devops with Azure"
    DURATION: "140HRS"
    TRAINER: "Gopal"
  tasks:
  - name: print the information
    ansible.builtin.debug:
     msg: "Hi, i am learning {{COURSE}},Duration is: {{DURATION}},Trainer: {{TRAINER}} "

  - name: print the information again
    vars: #task level variables
      COURSE: "Ansible"
    ansible.builtin.debug:
     msg: "Hi, i am learning {{COURSE}},Duration is: {{DURATION}},Trainer: {{TRAINER}} "

  - name: print the information agian and again
    ansible.builtin.debug:
     msg: "Hi, i am learning {{COURSE}},Duration is: {{DURATION}},Trainer: {{TRAINER}} "