- name: devops course information
  hosts: local
  vars:
    course: "devops with AWS"
    duration: "120 "
    topics:
    - ansible
    - linux
    - shell
    - docker
    - terrform
    - K8
    - AWS
    live: true
    tools:
    ci: jenkins
    cm: ansible
    cloud: AWS
    aws:
    - AMI
    - s3
  tasks:
  - name: print the course information
    ansible.builtin.debug:
      msg: "Hi, i am learning {{course}}, duration is {{duration}},topics are {{topics}}, and live: {{live}}, tools are {{tools}}"
  