- name: create user
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: check user exist or not
    ansible.builtin.command: id expense
    register: USER # here user is a variable that gets output for the above command
    ignore_errors: True

  - name: print the information
    ansible.builtin.debug:
      msg: " user info: {{USER}} "

  - name: create user
    ansible.builtin.command: useradd expense
    when: USER.rc !=0